spring:
  datasource:
    url: jdbc:mysql://test.cqtkqq2p1cfx.ap-northeast-2.rds.amazonaws.com:3306/batch
    username: root
    password: malangcute121!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
  batch:
    jdbc:
      initialize-schema: always # ??? ????
    job:
      enabled: false # ?? ?? ?? -> ??? ??? ?? jobRunner? ????? ??
  profiles:
    active: local
  sql:
    init:
      schema-locations: classpath:post.sql
      mode: EMBEDDED

